# Generated by Django 3.0.7 on 2020-07-17 11:18

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default=articles.models.Article.author_default, max_length=144),
        ),
    ]
