# Generated by Django 3.0.7 on 2020-07-17 13:06

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200717_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default=articles.models.Article.slug_default, max_length=255),
        ),
    ]
